# Generated by Django 4.2.5 on 2023-10-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrol_bunk',
            name='email',
            field=models.EmailField(default=3457, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petrol_bunk',
            name='password',
            field=models.CharField(default=9876543, max_length=128),
            preserve_default=False,
        ),
    ]
