# Generated by Django 4.2.5 on 2023-10-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_petrol_bunk_email_petrol_bunk_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petrol_bunk',
            old_name='img',
            new_name='imgage',
        ),
    ]
