# Generated by Django 4.2.5 on 2023-10-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_rename_img_petrol_bunk_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petrol_bunk',
            old_name='imgage',
            new_name='image',
        ),
    ]
