# Generated by Django 4.2.5 on 2023-10-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_rename_imgage_petrol_bunk_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
