# Generated by Django 4.2.5 on 2023-10-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_fuel_details_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuel_request',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
