# Generated by Django 4.2.5 on 2023-10-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_fuel_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('state_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
