# Generated by Django 4.2.6 on 2023-10-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_remove_fuel_request_fuel_type_fuel_request_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrol_bunk',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
