# Generated by Django 4.2.6 on 2023-10-29 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_petrol_bunk_active_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel_request',
            old_name='fuelid',
            new_name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='fuel_request',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='fuel_request',
            name='longitude',
        ),
    ]
