# Generated by Django 4.2.6 on 2023-11-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_fuel_request_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_details',
            name='Rate',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fuel_request',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
