# Generated by Django 4.2.7 on 2023-11-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application12', '0003_remove_register_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_center',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
