# Generated by Django 4.2.7 on 2023-11-11 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application12', '0004_service_center_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_request',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application12.service_center'),
        ),
        migrations.AlterField(
            model_name='service_request',
            name='reg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application12.register'),
        ),
    ]
