# Generated by Django 4.2.7 on 2023-11-12 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application12', '0007_service_request_service_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatroom',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_key', models.CharField(max_length=200)),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application12.service_center')),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application12.register')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('chatkey', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('from_id', models.IntegerField()),
                ('to_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application12.chatroom')),
            ],
        ),
    ]
