# Generated by Django 4.2.6 on 2023-10-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_patients_user_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance_drivers',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='driver_pic/'),
        ),
    ]
