# Generated by Django 4.2.6 on 2023-10-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_patient_id_user_reg_reg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance',
            fields=[
                ('ambulance_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(max_length=17, unique=True)),
                ('vehicle_status', models.BooleanField(default=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ambulance_drivers')),
            ],
        ),
    ]
