# Generated by Django 4.2.6 on 2023-10-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ambulance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ambulance/'),
        ),
    ]
