# Generated by Django 4.2.6 on 2023-10-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ambulance_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patient_details',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100)),
                ('reason', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Ride Completed', 'Ride Completed'), ('On the way', 'On the way'), ('Picked Patient', 'Picked patient')], max_length=100)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ambulance_drivers')),
                ('requestor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
    ]
