# Generated by Django 4.2.6 on 2023-10-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_state_country_id_alter_city_state_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='country_id',
            field=models.IntegerField(default=101),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='status',
            field=models.CharField(choices=[('Ride Completed', 'Ride Completed'), ('On the way', 'On the way'), ('Picked Patient', 'Picked patient')], max_length=100),
        ),
    ]
