# Generated by Django 4.2.6 on 2023-10-22 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_state_country_id_alter_patient_details_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_details',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='patient_details',
            name='status',
        ),
        migrations.AddField(
            model_name='patient_details',
            name='hospital',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='app.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100),
        ),
        migrations.CreateModel(
            name='booking_details',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booked_on', models.DateField(auto_now_add=True)),
                ('driver_status', models.CharField(choices=[('On the way', 'On the way'), ('Picked Patient', 'Picked patient'), ('Ride Completed', 'Ride Completed')], max_length=100)),
                ('booking_status', models.BooleanField(default=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ambulance_drivers')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient_details')),
            ],
        ),
    ]
