# Generated by Django 4.2.6 on 2023-10-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_patient_details_driver_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='city',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_details',
            name='state',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('Picked Patient', 'Picked patient'), ('On the way', 'On the way'), ('Ride Completed', 'Ride Completed')], max_length=100),
        ),
    ]
