# Generated by Django 4.2.6 on 2023-10-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_patient_details_city_patient_details_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hospitals/'),
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('Picked Patient', 'Picked patient'), ('Ride Completed', 'Ride Completed'), ('On the way', 'On the way')], max_length=100),
        ),
    ]
