# Generated by Django 4.2.6 on 2023-10-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_hospital_image_alter_booking_details_driver_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='district',
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('Ride Completed', 'Ride Completed'), ('On the way', 'On the way'), ('Picked Patient', 'Picked patient')], max_length=100),
        ),
    ]
