# Generated by Django 4.2.6 on 2023-10-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_hospital_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Picked Patient', 'Picked patient'), ('Ride Completed', 'Ride Completed')], default='Driver Assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
