# Generated by Django 4.2.6 on 2023-10-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_booking_details_driver_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance_drivers',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('Picked Patient', 'Picked patient'), ('Ride Completed', 'Ride Completed'), ('On the way', 'On the way')], default='Driver Assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100),
        ),
    ]
