# Generated by Django 4.2.6 on 2023-10-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_ambulance_drivers_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('Picked Patient', 'Picked patient'), ('On the way', 'On the way'), ('Ride Completed', 'Ride Completed')], default='Driver Assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
