# Generated by Django 4.2.6 on 2023-10-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_booking_details_booked_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Ride Completed', 'Ride Completed'), ('Picked Patient', 'Picked patient')], default='Driver Assigned', max_length=100),
        ),
    ]
