# Generated by Django 4.2.6 on 2023-10-24 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_booking_details_driver_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance_drivers',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='district',
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('Ride In Progress', 'Ride In Progress'), ('Ride Completed', 'Ride Completed'), ('Ride Started', 'Ride Started'), ('Picked Patient', 'Picked Patient')], default='Driver Assigned', max_length=100),
        ),
        migrations.CreateModel(
            name='rate',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate_count', models.IntegerField(default=0)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking_details')),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.TextField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking_details')),
            ],
        ),
    ]
