# Generated by Django 4.2.6 on 2023-10-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_complaints_complaint_status_complaints_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('Ride Started', 'Ride Started'), ('Ride In Progress', 'Ride In Progress'), ('Ride Completed', 'Ride Completed'), ('Picked Patient', 'Picked Patient')], default='Driver Assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='reply',
            field=models.TextField(blank=True, default=''),
        ),
    ]
