# Generated by Django 4.2.6 on 2023-10-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_booking_details_driver_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('Ride Completed', 'Ride Completed'), ('Picked Patient', 'Picked Patient'), ('Ride Started', 'Ride Started'), ('Ride In Progress', 'Ride In Progress')], default='Driver Assigned', max_length=100),
        ),
        migrations.CreateModel(
            name='driver_location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=300)),
                ('longitude', models.CharField(max_length=300)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ambulance_drivers')),
            ],
        ),
    ]
