# Generated by Django 4.2.6 on 2023-10-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_booking_details_driver_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('Ride Started', 'Ride Started'), ('Ride In Progress', 'Ride In Progress'), ('Ride Completed', 'Ride Completed'), ('Picked Patient', 'Picked Patient')], default='Driver Assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='driver_location',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='driver_location',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
