# Generated by Django 4.2.6 on 2023-10-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sewing_request_material_id2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sewing_request',
            name='material_id2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sewing_request',
            name='material_id3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
