# Generated by Django 4.2.6 on 2023-11-02 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_sewing_request_material_id2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewing_request',
            name='requested_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
