# Generated by Django 4.2.6 on 2023-11-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_sewing_details_fabric1_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sewing_details',
            name='tailor_status',
            field=models.CharField(default='Waiting For your Response', max_length=100),
        ),
    ]
