# Generated by Django 4.2.6 on 2023-11-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_sewing_details_ordered_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sewing_details',
            old_name='price',
            new_name='price1',
        ),
        migrations.AddField(
            model_name='sewing_details',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sewing_details',
            name='price3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sewing_details',
            name='sewing_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sewing_details',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
