# Generated by Django 4.2.6 on 2023-11-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_sewing_details_design_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewing_details',
            name='rate_given',
            field=models.BooleanField(default=False),
        ),
    ]
