# Generated by Django 4.2.6 on 2023-11-04 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_orders_agents_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='material_request',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_on', models.DateField(auto_now_add=True)),
                ('request_status', models.BooleanField(default=False)),
                ('manufacturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orders')),
            ],
        ),
    ]
