# Generated by Django 4.2.6 on 2023-11-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_orders_deliver_status_assign_delivery_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_agent_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='deliver_status',
            field=models.CharField(default='The delivery agent is still unassigned.', max_length=100),
        ),
    ]
