# Generated by Django 4.2.6 on 2023-11-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_assign_delivery_agent_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='pickup_status',
            field=models.BooleanField(default=False),
        ),
    ]
