# Generated by Django 4.2.6 on 2023-10-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_remove_customers_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recyling_unit',
            new_name='recycling_unit',
        ),
    ]
