# Generated by Django 4.2.6 on 2023-10-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_category_register_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='firstname',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='lastname',
            field=models.CharField(default=9876543, max_length=100),
            preserve_default=False,
        ),
    ]
