# Generated by Django 4.2.7 on 2023-11-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_product_expire_date_product_uploaded_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='product_status',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='street',
        ),
        migrations.RemoveField(
            model_name='recycling_unit',
            name='street',
        ),
        migrations.AddField(
            model_name='customers',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
        migrations.AddField(
            model_name='recycling_unit',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
