# Generated by Django 4.2.6 on 2023-10-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delivery_agent_profile_pic_designer_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_agent',
            name='usertype',
            field=models.IntegerField(default=6),
        ),
    ]
