# Generated by Django 4.2.6 on 2023-10-31 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sewing_measurements_sewing_request_sewing_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sewing_request',
            old_name='material_id',
            new_name='material_id1',
        ),
    ]
