# Generated by Django 4.2.6 on 2023-10-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_material_id_sewing_request_material_id1'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewing_request',
            name='material_id2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sewing_request',
            name='material_id3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sewing_request',
            name='material_id1',
            field=models.IntegerField(),
        ),
    ]
