# Generated by Django 4.2.6 on 2023-11-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_price_sewing_details_price1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewing_details',
            name='design_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
