# Generated by Django 4.2.6 on 2023-11-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_sewing_details_rate_given'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sewing_details',
            name='rate_given',
        ),
        migrations.AddField(
            model_name='sewing_request',
            name='rate_given',
            field=models.BooleanField(default=False),
        ),
    ]
