# Generated by Django 4.2.6 on 2023-11-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_orders_tailor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.BooleanField(default=True),
        ),
    ]
