# Generated by Django 4.2.6 on 2023-11-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_material_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_request',
            name='material_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='app.materials'),
            preserve_default=False,
        ),
    ]
