# Generated by Django 4.2.6 on 2023-11-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_material_request_material_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='material_req_status',
            field=models.BooleanField(default=False),
        ),
    ]
