# Generated by Django 4.2.6 on 2023-11-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_orders_material_req_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='deliver_status',
            field=models.CharField(default='Delivery agent has not yet assigned.', max_length=100),
        ),
        migrations.CreateModel(
            name='assign_delivery_agent',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('pickup_status', models.BooleanField(default=False)),
                ('deliver_status', models.BooleanField(default=False)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materials')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orders')),
            ],
        ),
    ]
