# Generated by Django 4.2.6 on 2023-11-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_orders_delivery_agent_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_delivery_agent',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.delivery_agent'),
        ),
    ]
