# Generated by Django 4.2.7 on 2023-11-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offences',
            fields=[
                ('offence_id', models.AutoField(primary_key=True, serialize=False)),
                ('offence', models.CharField(max_length=300)),
                ('details', models.CharField(max_length=300)),
                ('fine', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='offender',
            fields=[
                ('offender_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offense_images/')),
                ('offence_status', models.BooleanField(default=False)),
                ('fine_status', models.BooleanField(default=False)),
                ('offence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.offences')),
                ('officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.officers')),
                ('vehicle_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.vehicle_details', to_field='vehicle_no')),
            ],
        ),
        migrations.DeleteModel(
            name='offense',
        ),
        migrations.RemoveField(
            model_name='vehicle_details',
            name='vehicle_status',
        ),
    ]
