# Generated by Django 4.2.7 on 2023-11-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_traffic_rules_traffic_rule_violation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic_rule_violation',
            name='fine',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='offender',
        ),
    ]
