# Generated by Django 4.2.7 on 2023-11-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_offences_offenders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offences',
            name='vehicle_no',
            field=models.CharField(max_length=300),
        ),
    ]
