# Generated by Django 4.2.7 on 2023-11-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_offences_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offenders',
            name='offender_status',
            field=models.BooleanField(default=False),
        ),
    ]
