# Generated by Django 4.2.7 on 2023-11-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_offenders_offender_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offenders',
            name='offender_status',
            field=models.BooleanField(default=True),
        ),
    ]
