# Generated by Django 4.2.6 on 2023-10-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_customers_firstname_customers_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycling_unit',
            name='unit_name',
            field=models.CharField(default=8776, max_length=100),
            preserve_default=False,
        ),
    ]
