# Generated by Django 4.2.7 on 2023-11-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_alter_product_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_request',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_on', models.DateField(auto_now_add=True)),
                ('req_status', models.BooleanField(default=True)),
                ('approve_status', models.BooleanField(default=False)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='APP.customers')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='APP.customers')),
            ],
        ),
    ]
