# Generated by Django 4.2.7 on 2023-11-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_recycle_product_recycle_product_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycle_product_request',
            name='customer_id',
        ),
    ]
