# Generated by Django 4.2.7 on 2023-11-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_remove_recycle_product_request_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
