# Generated by Django 4.2.7 on 2023-11-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0018_product_rating_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycle_product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recycle_product',
            name='rating_status',
            field=models.BooleanField(default=True),
        ),
    ]
