from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('register/', views.register_func, name='register'),
    path('tailor_reg/', views.tailor_reg, name='tailor_reg'),
    path('manufacturer_reg/', views.manufacturer_reg, name='manufacturer_reg'),
    path('designer_reg/', views.designer_reg, name='designer_reg'),
    path('login/', views.login, name='login'),
    path('delivery_agent_reg/<int:uid>', views.delivery_agent_reg, name='delivery_agent_reg'),
    path('delivery_agent_list/<int:uid>', views.delivery_agent_list, name='delivery_agent_list'),
    path('admin_home/<int:uid>', views.admin_home, name='admin_home'),
    path('customer_home/<int:uid>', views.customer_home, name='customer_home'),
    path('manufacturer_home/<int:uid>', views.manufacturer_home, name='manufacturer_home'),
    path('tailor_home/<int:uid>', views.tailor_home, name='tailor_home'),
    path('designer_home/<int:uid>', views.designer_home, name='designer_home'),
    path('delivery_agent_home/<int:uid>', views.delivery_agent_home, name='delivery_agent_home'),
    path('approvetailors/<int:uid>', views.approvetailors, name='approvetailors'),
    path('approve_tailor/<int:uid>/<int:id>', views.approve_tailor, name='approve_tailor'),
    path('reject_tailor/<int:uid>/<int:id>', views.reject_tailor, name='reject_tailor'),
    path('approvedesigners/<int:uid>', views.approvedesigners, name='approvedesigners'),
    path('approve_designer/<int:uid>/<int:id>', views.approve_designer, name='approve_designer'),
    path('reject_designer/<int:uid>/<int:id>', views.reject_designer, name='reject_designer'),
    path('approvemanufacturers/<int:uid>', views.approvemanufacturers, name='approvemanufacturers'),
    path('approve_manufacturer/<int:uid>/<int:id>', views.approve_manufacturer, name='approve_manufacturer'),
    path('reject_manufacturer/<int:uid>/<int:id>', views.reject_manufacturer, name='reject_manufacturer'),
    path('tailor_list/<int:uid>', views.tailor_list, name='tailor_list'),
    path('manufacturer_list/<int:uid>', views.manufacturer_list, name='manufacturer_list'),
    path('designer_list/<int:uid>', views.designer_list, name='designer_list'),
    path('customer_list/<int:uid>', views.customer_list, name='customer_list'),
    path('delivery_agent_list/<int:uid>', views.delivery_agent_list, name='delivery_agent_list'),
    path('delete_delivery_agent/<int:uid>/<int:id>', views.delete_delivery_agent, name='delete_delivery_agent'),
    path('delete_tailor/<int:uid>/<int:id>', views.delete_tailor, name='delete_tailor'),
    path('delete_customer/<int:uid>/<int:id>', views.delete_customer, name='delete_customer'),
    path('delete_designer/<int:uid>/<int:id>', views.delete_designer, name='delete_designer'),
    path('delete_manufacturer/<int:uid>/<int:id>', views.delete_manufacturer, name='delete_manufacturer'),
    path('admin_profile/<int:uid>', views.admin_profile, name='admin_profile'),
    path('edit_admin_profile/<int:uid>', views.edit_admin_profile, name='edit_admin_profile'),
    path('customer_profile/<int:uid>', views.customer_profile, name='customer_profile'),
    path('edit_customer_profile/<int:uid>', views.edit_customer_profile, name='edit_customer_profile'),
    path('manufacturer_profile/<int:uid>', views.manufacturer_profile, name='manufacturer_profile'),
    path('edit_manufacturer_profile/<int:uid>', views.edit_manufacturer_profile, name='edit_manufacturer_profile'),
    path('designer_profile/<int:uid>', views.designer_profile, name='designer_profile'),
    path('edit_designer_profile/<int:uid>', views.edit_designer_profile, name='edit_designer_profile'),
    path('tailor_profile/<int:uid>', views.tailor_profile, name='tailor_profile'),
    path('edit_tailor_profile/<int:uid>', views.edit_tailor_profile, name='edit_tailor_profile'),
    path('category_list/<int:uid>', views.category_list, name='category_list'),
    path('add_category/<int:uid>', views.add_category, name='add_category'),
    path('delete_category/<int:uid>/<int:id>', views.delete_category, name='delete_category'),
    path('edit_category/<int:uid>/<int:id>', views.edit_category, name='edit_category'),
    path('designs_list/<int:uid>', views.designs_list, name='designs_list'),
    path('add_design/<int:uid>', views.add_design, name='add_design'),
    path('edit_design/<int:uid>/<int:id>', views.edit_design, name='edit_design'),
    path('delete_design/<int:uid>/<int:id>', views.delete_design, name='delete_design'),
    path('admin_designs_list/<int:uid>', views.admin_designs_list, name='admin_designs_list'),
    path('admin_delete_design/<int:uid>/<int:id>', views.admin_delete_design, name='admin_delete_design'),
    path('materials_list/<int:uid>', views.materials_list, name='materials_list'),
    path('add_material/<int:uid>', views.add_material, name='add_material'),
    path('edit_material/<int:uid>/<int:id>', views.edit_material, name='edit_material'),
    path('delete_material/<int:uid>/<int:id>', views.delete_material, name='delete_material'),
    path('admin_materials_list/<int:uid>', views.admin_materials_list, name='admin_materials_list'),
    path('admin_delete_material/<int:uid>/<int:id>', views.admin_delete_material, name='admin_delete_material'),
    path('get_designs/<int:uid>/<int:id>', views.get_designs, name='get_designs'),
    path('design_more_details/<int:uid>/<int:id>', views.design_more_details, name='design_more_details'),
    path('request_tailor/<int:uid>/<int:id>', views.request_tailor, name='request_tailor'),
    path('view_sew_requests/<int:uid>', views.view_sew_requests, name='view_sew_requests'),
    path('accept_request/<int:uid>/<int:id>', views.accept_request, name='accept_request'),
    path('reject_request/<int:uid>/<int:id>', views.reject_request, name='reject_request'),
    path('track_request/<int:uid>/<int:id>', views.track_request, name='track_request'),
    path('customer_track_request/<int:uid>/<int:id>', views.customer_track_request, name='customer_track_request'),
    path('customer_request_history/<int:uid>', views.customer_request_history, name='customer_request_history'),
    path('cancel_request/<int:uid>/<int:id>', views.cancel_request, name='cancel_request'),
    path('customer_orders/<int:uid>', views.customer_orders, name='customer_orders'),
    path('give_measurement/<int:uid>/<int:id>', views.give_measurement, name='give_measurement'),
    path('tailor_order_list/<int:uid>', views.tailor_order_list, name='tailor_order_list'),
    path('give_rate_details/<int:uid>/<int:id>', views.give_rate_details, name='give_rate_details'),
    path('accept_order_rate/<int:uid>/<int:id>', views.accept_order_rate, name='accept_order_rate'),
    path('reject_order_rate/<int:uid>/<int:id>', views.reject_order_rate, name='reject_order_rate'),
    path('sewing_rate_details/<int:uid>/<int:id>', views.sewing_rate_details, name='sewing_rate_details'),
    path('order_placed/<int:uid>', views.order_placed, name='order_placed'),
    path('my_orders/<int:uid>', views.my_orders, name='my_orders'),
    path('customer_order_history/<int:uid>', views.customer_order_history, name='customer_order_history'),
    path('tailor_orders/<int:uid>', views.tailor_orders, name='tailor_orders'),
    path('tailor_order_details/<int:uid>/<int:id>', views.tailor_order_details, name='tailor_order_details'),
    path('tailor_order_history/<int:uid>', views.tailor_order_history, name='tailor_order_history'),
    path('material_requests/<int:uid>/<int:sewing_id>/<int:material_id>', views.material_requests, name='material_requests'),
    path('fabric_request/<int:uid>', views.fabric_request, name='fabric_request'),
    path('material_requests_list/<int:uid>', views.material_requests_list, name='material_requests_list'),
    path('material_requests_history/<int:uid>', views.material_requests_history, name='material_requests_history'),
    path('accept_material_request/<int:uid>/<int:id>/<int:order_id>', views.accept_material_request, name='accept_material_request'),
    path('update_tailor_status/<int:uid>/<int:id>', views.update_tailor_status, name='update_tailor_status'),
    path('delivery_agent_orders/<int:uid>', views.delivery_agent_orders, name='delivery_agent_orders'),
    path('delivery_agent_order_history/<int:uid>', views.delivery_agent_order_history, name='delivery_agent_order_history'),
    path('pickup_order/<int:uid>/<int:id>/', views.pickup_order, name='pickup_order'),
    path('deliver_order/<int:uid>/<int:id>/', views.deliver_order, name='deliver_order'),




    path('get_categories/', views.get_categories, name='get_categories'),
    path('logout/', views.logout, name='logout'),






    # path('inc_qty/<int:uid>/<int:item_id>', views.inc_qty, name='inc_qty'),
    # path('dnc_qty/<int:uid>/<int:item_id>', views.dnc_qty, name='dnc_qty'),
    # path('add_to_cart/<int:uid>/<int:products_id>', views.add_to_cart, name='add_to_cart'),
    # path('remove_cart_item/<int:uid>/<int:id>/<int:cart_id>', views.remove_cart_item, name='remove_cart_item'),
    # path('carts/<int:uid>/', views.carts, name='carts'),
    # path('place_order/<int:uid>/<int:carts_id>', views.place_order, name='place_order'),
    # path('checkout/<int:uid>/<str:total_price>/<int:cart_id>', views.checkout, name='checkout'),
    # path('order_history/<int:uid>', views.order_history, name='order_history'),
    # path('new_order/<int:uid>', views.new_order, name='new_order'),
    # path('delivery_agent_orders/<int:uid>', views.delivery_agent_orders, name='delivery_agent_orders'),
    # path('pickup_order/<int:uid>/<int:id>/', views.pickup_order, name='pickup_order'),
    # path('deliver_order/<int:uid>/<int:id>/', views.deliver_order, name='deliver_order'),

]