from django .urls import path,include
from . import views
urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.reg,name='register'),
    path('service_center_register/',views.service_center_register,name='service_center_register'),
    path('login/',views.login,name='login'),
    path('user_home/<int:uid>',views.user_home,name='user_home'),
    path('admin_home/<int:uid>',views.admin_home,name='admin_home'),
    path('service_center_home/<int:uid>',views.Service_center_home,name='service_center_home'),
    path('admin_profile/<int:uid>',views.admin_profile,name='admin_profile'),
    path('edit_profile/<int:uid>',views.edit_profile,name='edit_profile'),
    path('edit_service_center_profile/<int:uid>',views.edit_service_center_profile,name='edit_service_center_profile'),
    path('Approveservicecenterlist/<int:uid>',views.Approveservicecenterlist,name='Approveservicecenterlist'),
    path('profile/<int:id>', views.profile, name='profile'),
    path('approveservice_center/<int:uid>/<int:id>', views.approveservice_center, name='approveservice_center'),
    path('rejectservice_center/<int:uid>/<int:id>', views.rejectservice_center, name='rejectservice_center'),
    path('deleteServiceCenter/<int:uid>/<int:id>', views.deleteServiceCenter, name='deleteServiceCenter'),
    path('deleteCustomer/<int:uid>/<int:id>', views.deleteCustomer, name='deleteCustomer'),
    path('ServiceCenterList/<int:uid>',views.ServiceCenterList,name='ServiceCenterList'),
    path('CustomerList/<int:uid>' ,views.CustomerList,name='CustomerList'),
    ###path('customer_profile/<int:uid>',views.customer_profile,name='customer_profile'),
    path('user_profile/<int:uid>',views.user_profile,name='user_profile'),
    path('edit_user_profile/<int:uid>',views.edit_user_profile,name='edit_user_profile'),
    path('service_center_profile/<int:uid>',views.service_center_profile,name='service_center_profile'),
    path('get_states/',views.get_states,name='get_states'),
    path('get_cities/',views.get_cities,name='get_cities'),
    path('user_service_request/<int:uid>/<int:id>', views.user_service_request, name='user_service_request'),
    path('view_service_request/<int:uid>', views.view_service_request, name='view_service_request'),
    path('approve_request/<int:uid>/<int:id>', views.approve_request, name='approve_request'),
    path('reject_request/<int:uid>/<int:id>', views.reject_request, name='reject_request'),
    path('user_my_request/<int:uid>', views.user_my_request, name='user_my_request'),
    path('cancel_request/<int:uid>/<int:id>', views.cancel_request, name='cancel_request'),
    path('current_service/<int:uid>', views.current_service, name='current_service'),
    path('previous_services/<int:uid>', views.previous_services, name='previous_services'),
    path('complete_service/<int:uid>/<int:id>', views.complete_service, name='complete_service'),
    path('user_current_service/<int:uid>', views.user_current_service, name='user_current_service'),
    path('user_previous_services/<int:uid>', views.user_previous_services, name='user_previous_services'),
    path('create_chat/<int:uid>/<int:id>/', views.create_chat, name='create_chat'),
    path('user_chat/<int:uid>/<int:id>/<str:chat_key>', views.user_chat, name='user_chat'),
    path('center_create_chat/<int:uid>/<int:id>/', views.center_create_chat, name='center_create_chat'),
    path('center_chat/<int:uid>/<int:id>/<str:chat_key>', views.center_chat, name='center_chat'),
    path('previous_center_chat/<int:uid>/<int:id>', views.previous_center_chat, name='previous_center_chat'),
    path('previous_user_chat/<int:uid>/<int:id>', views.previous_user_chat, name='previous_user_chat'),

    path('logout/', views.logout, name='logout'),

    path('create_user_message/', views.create_user_message, name='create_user_message'),
    path('create_center_message/', views.create_center_message, name='create_center_message'),
    path('get_chat_messages/<str:chat_key>/', views.get_chat_messages, name='get_chat_messages'),
    path('get_center_chat_messages/<str:chat_key>/', views.get_center_chat_messages, name='get_center_chat_messages'),
    path('get_service_center_status/', views.get_service_center_status, name='get_service_center_status'),
    path('activate_service_center/', views.activate_service_center, name='activate_service_center'),
    path('nearby_service_centers/<int:uid>/<centers>', views.nearby_service_centers, name='nearby_service_centers'),
    path('get_nearby_service_centers/', views.get_nearby_service_centers, name='get_nearby_service_centers'),

]
