# Generated by Django 4.2.6 on 2023-10-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exterior_Designer',
            fields=[
                ('exterior_designer_id', models.AutoField(primary_key=True, serialize=False)),
                ('architect_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField(auto_now=True)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('qualifications', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='exterior_designer_photo/')),
                ('experience', models.CharField(max_length=50)),
                ('user_type', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Interior_Designer',
            fields=[
                ('interior_designer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField(auto_now=True)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='interior_designer_photo/')),
                ('experience', models.CharField(max_length=50)),
                ('user_type', models.IntegerField(default=4)),
            ],
        ),
        migrations.RenameField(
            model_name='architect',
            old_name='qualification',
            new_name='qualifications',
        ),
        migrations.AddField(
            model_name='architect',
            name='user_type',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_type',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='architect',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='architect_photo/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photo/'),
        ),
    ]
