# Generated by Django 4.2.6 on 2023-10-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_exterior_designer_interior_designer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='password',
            field=models.CharField(default='your_default_password', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='your_default_password', max_length=100),
        ),
        migrations.AddField(
            model_name='exterior_designer',
            name='password',
            field=models.CharField(default='your_default_password', max_length=100),
        ),
        migrations.AddField(
            model_name='interior_designer',
            name='password',
            field=models.CharField(default='your_default_password', max_length=100),
        ),
    ]
