# Generated by Django 4.2.6 on 2023-10-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_architect_password_customer_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exterior_designer',
            old_name='architect_name',
            new_name='name',
        ),
    ]
