# Generated by Django 4.2.6 on 2023-10-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_architect_name_exterior_designer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exterior_designer',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='interior_designer',
            name='dob',
            field=models.DateField(),
        ),
    ]
