# Generated by Django 4.2.6 on 2023-10-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
