# Generated by Django 4.2.6 on 2023-10-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_architect_dob_remove_architect_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
