# Generated by Django 4.2.6 on 2023-10-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exterior_designer',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interior_designer',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
