# Generated by Django 4.2.6 on 2023-10-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_phone_architect_phone_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
    ]
