# Generated by Django 4.2.6 on 2023-10-24 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_architect_address_alter_architect_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=50)),
                ('sqft', models.CharField(max_length=30)),
                ('floor', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('budget', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plan_image/')),
                ('status', models.BooleanField(default=False)),
                ('architect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.architect')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Book',
            fields=[
                ('plan_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('book_date', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.plan')),
            ],
        ),
    ]
