# Generated by Django 4.2.6 on 2023-10-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_plan_plan_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='image',
            new_name='plan_image',
        ),
    ]
