# Generated by Django 4.2.6 on 2023-11-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_image_plan_plan_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interior_Design',
            fields=[
                ('interior_design_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=100)),
                ('budgets', models.CharField(max_length=50)),
                ('interior_design_image', models.ImageField(blank=True, null=True, upload_to='interior_design_image/')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('interior_designer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.interior_designer')),
            ],
        ),
        migrations.CreateModel(
            name='Exterior_Design',
            fields=[
                ('exterior_design_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=100)),
                ('budgets', models.CharField(max_length=50)),
                ('exterior_design_image', models.ImageField(blank=True, null=True, upload_to='exterior_design_image/')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('exterior_designer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.exterior_designer')),
            ],
        ),
    ]
