# Generated by Django 4.2.6 on 2023-11-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_interior_design_exterior_design'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exterior_design',
            old_name='budgets',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='interior_design',
            old_name='budgets',
            new_name='budget',
        ),
    ]
