# Generated by Django 4.2.6 on 2023-11-12 04:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_rename_budgets_exterior_design_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_book',
            name='architect_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.architect'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan_book',
            name='requested_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 11, 12, 4, 29, 38, 968010, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
