# Generated by Django 4.2.6 on 2023-11-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_plan_book_architect_id_plan_book_requested_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_book',
            name='book_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
