# Generated by Django 4.2.6 on 2023-11-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_plan_book_book_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='INT_design_book',
            fields=[
                ('interior_design_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('requested_on', models.DateField(auto_now_add=True)),
                ('book_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
                ('interior_design_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.interior_design')),
                ('interior_designer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.interior_designer')),
            ],
        ),
        migrations.CreateModel(
            name='EXT_design_book',
            fields=[
                ('exterior_design_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('requested_on', models.DateField(auto_now_add=True)),
                ('book_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
                ('exterior_design_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.exterior_design')),
                ('exterior_designer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.exterior_designer')),
            ],
        ),
    ]
