# Generated by Django 4.2.7 on 2023-11-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_offences_traffic_rules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='traffic_rules',
            new_name='traffic_rule_violation',
        ),
        migrations.RenameField(
            model_name='traffic_rule_violation',
            old_name='offence',
            new_name='violation',
        ),
        migrations.RenameField(
            model_name='traffic_rule_violation',
            old_name='offence_id',
            new_name='violation_id',
        ),
    ]
