# Generated by Django 4.2.7 on 2023-11-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_traffic_rule_violation_fine_delete_offender'),
    ]

    operations = [
        migrations.CreateModel(
            name='offences',
            fields=[
                ('offence_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offense_images/')),
                ('reported_on', models.DateField(auto_now_add=True)),
                ('offence_status', models.BooleanField(default=False)),
                ('officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.officers')),
                ('vehicle_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.vehicle_details', to_field='vehicle_no')),
                ('violation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.traffic_rule_violation')),
            ],
        ),
        migrations.CreateModel(
            name='offenders',
            fields=[
                ('offender_id', models.AutoField(primary_key=True, serialize=False)),
                ('verified_on', models.DateField(auto_now_add=True)),
                ('fine_paid_on', models.DateField(blank=True, null=True)),
                ('fine_status', models.BooleanField(default=False)),
                ('offence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.offences')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
    ]
