# Generated by Django 4.2.7 on 2023-11-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_offences_vehicle_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='offences',
            name='reporter_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.register'),
            preserve_default=False,
        ),
    ]
