# Generated by Django 4.2.7 on 2023-11-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application12', '0002_city_state_service_center_id_service_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='district',
        ),
        migrations.RemoveField(
            model_name='service_center',
            name='district',
        ),
        migrations.AddField(
            model_name='service_center',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
