# Generated by Django 4.2.7 on 2023-11-11 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application12', '0005_alter_service_request_center_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='requested_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 11, 11, 20, 26, 38, 849847, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
