# Generated by Django 4.2.7 on 2023-11-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application12', '0006_service_request_requested_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='service_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service_request',
            name='req_status',
            field=models.BooleanField(default=True),
        ),
    ]
