from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.first, name='first'),
    path('index/', views. index, name='index'),
    path('login/', views.login, name='login'),
    path('about/', views.about, name='about'),
    path('register/', views.register_func, name='register'),
    path('officer_reg/<int:uid>', views.officer_reg, name='officer_reg'),
    path('service/', views.service, name='service'),
    path('first/', views.first, name='first'),
    path('contact/', views.contact, name='contact'),
    path('admin_profile/<int:uid>', views.admin_profile, name='admin_profile'),
    path('edit_admin_profile/<int:uid>', views.edit_admin_profile, name='edit_admin_profile'),
    # path('admin_offense_list/<int:uid>', views.admin_offense_list, name='admin_offense_list'),
    path('user_profile/<int:uid>', views.user_profile, name='user_profile'),
    path('edit_user_profile/<int:uid>', views.edit_user_profile, name='edit_user_profile'),
    path('officers_home/<int:uid>', views.officers_home, name='officers_home'),
    path('adhome/<int:uid>', views.admin_home, name='adhome'),
    path('users_home/<int:uid>', views.users_home, name='users_home'),
    path('approve_users/<int:uid>/<int:id>/', views.approve_users, name='approve_users'),
    path('approveusers/<int:uid>/', views.approveusers, name='approveusers'),
    path('reject_users/<int:uid>/<int:id>/', views.reject_users, name='reject_users'),
    path('add_vehicle_details/<int:uid>', views.add_vehicle_details, name='add_vehicle_details'),
    path('edit_vehicle/<int:uid>/<int:id>', views.edit_vehicle, name='edit_vehicle'),
    path('delete_vehicle/<int:uid>/<int:id>', views.delete_vehicle, name='delete_vehicle'),
    path('view_vehicles/<int:uid>', views.view_vehicles, name='view_vehicles'),
    path('officer_profile/<int:uid>', views.officer_profile, name='officer_profile'),
    path('edit_officer_profile/<int:uid>', views.edit_officer_profile, name='edit_officer_profile'),
    path('users_list/<int:uid>', views.users_list, name='users_list'),
    path('officers_list/<int:uid>', views.officers_list, name='officers_list'),
    path('delete_user/<int:uid>/<int:id>', views.delete_user, name='delete_user'),
    path('delete_officers/<int:uid>/<int:id>', views.delete_officers, name='delete_officers'),
    path('admin_view_violations_list/<int:uid>',views.admin_view_violations_list,name='admin_view_violations_list'),
    path('violations_list/<int:uid>',views.violations_list,name='violations_list'),
    path('add_violations/<int:uid>', views.add_violations, name='add_violations'),
    path('delete_violation/<int:uid>/<int:id>', views.delete_violation, name='delete_violation'),
    path('edit_violations/<int:uid>/<int:id>', views.edit_violations, name='edit_violations'),
    path('report_offence/<int:uid>', views.report_offence, name='report_offence'),
    path('reported_offences/<int:uid>', views.reported_offences, name='reported_offences'),
    path('edit_reported_offence/<int:uid>/<int:id>', views.edit_reported_offence, name='edit_reported_offence'),
    path('delete_reported_offence/<int:uid>/<int:id>', views.delete_reported_offence, name='delete_reported_offence'),
    path('admin_reported_offences/<int:uid>', views.admin_reported_offences, name='admin_reported_offences'),
    path('admin_delete_reported_offence/<int:uid>/<int:id>', views.admin_delete_reported_offence, name='admin_delete_reported_offence'),
    path('officer_reported_offences/<int:uid>', views.officer_reported_offences, name='officer_reported_offences'),
    path('verify_offender/<int:uid>/<int:id>/<str:vehicle_no>', views.verify_offender, name='verify_offender'),
    path('my_offences/<int:uid>', views.my_offences, name='my_offences'),
    path('offenders_list/<int:uid>', views.offenders_list, name='offenders_list'),
    path('fine_collected/<int:uid>/<int:id>', views.fine_collected, name='fine_collected'),
    path('fine_paid/<int:uid>', views.fine_paid, name='fine_paid'),
    path('user_fine_paid/<int:uid>', views.user_fine_paid, name='user_fine_paid'),
    path('admin_offenders_list/<int:uid>', views.admin_offenders_list, name='admin_offenders_list'),
    path('non_user_offenders_list/<int:uid>', views.non_user_offenders_list, name='non_user_offenders_list'),
    path('admin_non_user_offenders_list/<int:uid>', views.admin_non_user_offenders_list, name='admin_non_user_offenders_list'),

    path('logout/',views.logout,name='logout'),
    path('get_states/',views.get_states,name='get_states'),
    path('get_cities/',views.get_cities,name='get_cities'),
    path('get_officers/',views.get_officers,name='get_officers'),
    path('new_request/',views.new_request,name='new_request'),
    path('offender_notification/',views.offender_notification,name='offender_notification'),

]
