# Generated by Django 4.2.6 on 2023-10-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patients',
            new_name='user_reg',
        ),
    ]
