# Generated by Django 4.2.6 on 2023-10-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ambulance_drivers_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_reg',
            old_name='patient_id',
            new_name='reg_id',
        ),
    ]
