# Generated by Django 4.2.6 on 2023-10-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_state_patient_details_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='country_id',
            field=models.IntegerField(default=101),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='status',
            field=models.CharField(choices=[('Ride Completed', 'Ride Completed'), ('Picked Patient', 'Picked patient'), ('On the way', 'On the way')], max_length=100),
        ),
    ]
