# Generated by Django 4.2.6 on 2023-10-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_booking_details_driver_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='booked_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('Ride Completed', 'Ride Completed'), ('On the way', 'On the way'), ('Picked Patient', 'Picked patient')], default='Driver Assigned', max_length=100),
        ),
    ]
