# Generated by Django 4.2.6 on 2023-10-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_booking_details_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(default='Driver Assigned', max_length=100),
        ),
    ]
