# Generated by Django 4.2.6 on 2023-10-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_booking_details_driver_status_driver_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='latitude',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_details',
            name='longitude',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('Ride In Progress', 'Ride In Progress'), ('Picked Patient', 'Picked Patient'), ('Ride Completed', 'Ride Completed'), ('Ride Started', 'Ride Started')], default='Driver Assigned', max_length=100),
        ),
    ]
