# Generated by Django 4.2.6 on 2023-10-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_booking_details_driver_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='driver_status',
            field=models.CharField(choices=[('Ride In Progress', 'Ride In Progress'), ('Ride Started', 'Ride Started'), ('Picked Patient', 'Picked Patient'), ('Ride Completed', 'Ride Completed')], default='Driver Assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
